### ISSUE TITLE
Create IGV batch or session file to automate loading of prepared files

### ISSUE THREAD

**Issue by keithcallenberg** [FusionInspector/FusionInspector#1]
Would it be possible and make sense to construct either an IGV [batch](https://www.broadinstitute.org/software/igv/batch) or [session](https://www.broadinstitute.org/igv/Sessions) file to make it simpler to load FusionInspector results into IGV? In other words, a script to get IGV looking like the screenshot on the wiki page (without the mouse clicks). Would such a PR be considered?

**Comment by brianjohnhaas** [comment]
Sounds good to me!   If you have an example, we could start from there.  We
have a galaxy plugin for web-based igv.js visualization that folks can use
from our Trinity galaxy site, but the igv helper would be useful in other
situations.

thx!

~b

On Wed, May 18, 2016 at 11:53 AM, Keith Callenberg <notifications@github.com
> wrote:

> Would it be possible and make sense to construct either an IGV batch
> <https://www.broadinstitute.org/software/igv/batch> or session
> <https://www.broadinstitute.org/igv/Sessions> file to make it simpler to
> load FusionInspector results into IGV? In other words, a script to get IGV
> looking like the screenshot on the wiki page. Would such a PR be considered?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/FusionInspector/FusionInspector/issues/1>
>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas <http://broad.mit.edu/~bhaas>

**Comment by fgvieira** [comment]
Has this feature been implemented? I've been looking for some way to specify on a file all input files I want to load (CRAM, bigWig, several VCFs and BED), but with limited success.

**Comment by keithcallenberg** [comment]
@fgvieira I never found an opportunity to get this done, but I don't think it should be very difficult to implement.

**Comment by fgvieira** [comment]
Can it be done with a batch file? For example:
```
new
load REF.fa
load depth.10kb.bigwig
load discordants.bam
load FILE1.bed
load FILE2.bed
load FILE3.bed
load FILE4.bed
```

and then call IGV with:
```
igv.bat -b BATCH_FILE 
```

**Comment by keithcallenberg** [comment]
Yes something like that should work. That was effectively what I would do
manually. It would be cool if that could be made as a programmatic feature
of FusionInspector.

**Comment by brianjohnhaas** [comment]
Igv HTML reports are generated instead.  Use --vis

-via googleFi
