### ISSUE TITLE
FusionInspector visualization

### ISSUE THREAD

**Issue by bynjh007** [FusionInspector/FusionInspector#32]
Hi,
I got the results using STAR-Fusion with FusionInspector options like this:
'STAR-Fusion --FusionInspector validate --examine_coding_effect --left_fq {input.R1} --right_fq {input.R2} --genome_lib_dir {params.reflib} --CPU {threads} --output_dir {params.out_dir}'

From the results, there is a "FusionInspector-validate folder" which seems to be outputs of FusionInspector and also "finspector.fusion_inspector_web.json" file.

1. Can I make "finspector.fusion_inspector_web.html" file from "json" file for more efficient navigation of the results?
2. Can I get that html file from STAR-Fusion - embedded FusionInspector? (like add more parameter from above command?)

Thanks!

**Comment by brianjohnhaas** [comment]
Hi

The very latest code release should generate the HTML report file.


-via googleFi
