### ISSUE TITLE
Empty results

### ISSUE THREAD

**Issue by PrincescaDorsaint** [FusionInspector/FusionInspector#44]
Hi,

I am running FusionInspector using Docker. When running FusionInspector on the test data, I get the correct results. However, when I run FusionInspector on my STAR fusion results and .fastq.gz I get empty files. The pipeline runs however the "finspector.FusionInspector.fusions.abridged.tsv" files and so on are all empty.

**Comment by brianjohnhaas** [comment]
Hi Princesca,

Be sure that the fusion gene names given to FusionInspector match what's
being used for the reference annotations in the CTAT genome lib.

The easiest thing to do is to run STAR-Fusion first to capture the fusions,
and then FusionInspector given that list of fusions.     STAR-Fusion can be
run with option --FusionInspector validate  to confirm any STAR-Fusion
predictions.

All gene symbols recognized by STAR-Fusion can be found in the gene symbol
column of the file ctat_genome_lib_build_dir/ref_annot.gtf.gene_spans
of the ctat genome lib.

best,

~brian



On Wed, Aug 26, 2020 at 9:24 AM Princesca Dorsaint <notifications@github.com>
wrote:
>
> Hi,
>
> I am running FusionInspector using Docker. When running FusionInspector
on the test data, I get the correct results. However, when I run
FusionInspector on my STAR fusion results and .fastq.gz I get empty files.
The pipeline runs however the
"finspector.FusionInspector.fusions.abridged.tsv" files and so on are all
empty.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by PrincescaDorsaint** [comment]
Thanks Brian, it works now.

Thanks,
Princesca
