### ISSUE TITLE
Error in RT_artifact_inspector.Rscript

### ISSUE THREAD

**Issue by dshafranskaya** [FusionInspector/FusionInspector#64]
I tried to run FusionInspector with --incl_microH_expr_brkpt_plots parameter, but when processing one of fusions I got follow error due its name: 

processing: THRA--THRA1/BTR
Error in pdf(file.path(plots_dir, paste0(fusion_name, ".pdf"))) : 
  cannot open file 'microH_expr_brkpt_plots/THRA--THRA1/BTR.pdf'

**Comment by brianjohnhaas** [comment]
Thanks for pointing this out.

Drop in this updated script as a replacement:
https://github.com/FusionInspector/FusionInspector/blob/master/util/misc/RT_artifact_inspector.Rscript

and you can resume your earlier run by just rerunning the original command.

Let me know if this gives you any trouble.

best,

~brian

On Wed, Nov 23, 2022 at 4:27 AM dshafranskaya ***@***.***> wrote:
>
> I tried to run FusionInspector with --incl_microH_expr_brkpt_plots parameter, but when processing one of fusions I got follow error due its name:
>
> processing: THRA--THRA1/BTR
> Error in pdf(file.path(plots_dir, paste0(fusion_name, ".pdf"))) :
> cannot open file 'microH_expr_brkpt_plots/THRA--THRA1/BTR.pdf'
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas

**Comment by dshafranskaya** [comment]
Thanks for your answer! It works. But I got other error. I have sample with a lot of fusions, namely 83, and after processing 63 fusions I got following message: 

...
processing: ST3GAL1--NDRG1
Error in grDevices::pdf(NULL, width = width, height = height) : 
Execution halted
too many open devices
Calls: plot_grid ... as_gtable.default -> as_grob -> as_grob.ggplot -> device -> <Anonymous>

Can you help with this problem, please?

**Comment by brianjohnhaas** [comment]
Hi,

Happy to look into it, but I'd need to see the data that's causing the
issue.  If you could see what command is running at this step and send
me that command along with the corresponding input files to it, I'll
be able to dig deeper.  You can send privately to

bhaas at broadinstitute dot org

best,

~b

On Tue, Nov 29, 2022 at 2:20 AM dshafranskaya ***@***.***> wrote:
>
> Thanks for your answer! It works. But I got other error. I have sample with a lot of fusions, namely 83, and after processing 63 fusions I got following message:
>
> ...
> processing: ST3GAL1--NDRG1
> Error in grDevices::pdf(NULL, width = width, height = height) :
> Execution halted
> too many open devices
> Calls: plot_grid ... as_gtable.default -> as_grob -> as_grob.ggplot -> device ->
>
> Can you help with this problem, please?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>



-- 
--
Brian J. Haas
The Broad Institute
http://broadinstitute.org/~bhaas
